#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of custom HTTP header must be X-Served-By
# The value of custom HTTP header must be the hostname of the server Nginx is running on
#sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default 
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
echo 'Hello World!' |sudo tee /var/www/html/index.html

custom_header="server_name _;\n\tadd_header X-Served-By \$HOSTNAME;"
sudo sed -i "s|server_name _;|$custom_header|" /etc/nginx/sites-enabled/default
sudo service nginx restart
