#!/usr/bin/env bash
# installs nginx with the configuration
#+ Listen on port 80.
#+ Returns page containing "Hello World!"
#++ at root with a curl GET 

apt-get -y update
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.html
service nginx restart
